Feat/agent builder page
kyegomez/swarms-platform pull request #129
Opened 2024-07-02 20:14 UTC by Tunki1201

Feat/agent builder page

2024-07-02 22:17 UTC, gilbertoaceville requested changes

2024-07-02 22:17 UTC, gilbertoaceville commented on package.json
>      "@radix-ui/react-slider": "^1.1.2",
Do we need some of these radix ui packages? We've already got some of them, like `input,` did you compare? Are there special setups with `labels`?

2024-07-02 22:17 UTC, gilbertoaceville commented on modules/platform/agentbuilder/index.tsx
> +                        <Textarea id="systemPrompt" placeholder="Enter system prompt" rows={3} />
Do we need radix ui for elements like `label` and `textarea`? We've done a clean-up and are trying not to bloat the code base with unnecessary packages.

Are there specific reasons we can't reuse some components we already have like `input`?

2024-07-03 02:12 UTC, Tunki1201 commented on modules/platform/agentbuilder/index.tsx
> +                        <Textarea id="systemPrompt" placeholder="Enter system prompt" rows={3} />
as you know,  https://v0.dev/t/jkrUiNSmhPr
you can see the code snippet here.
In this code they used @radix-ui
and also I know the shared components in our project, but there are a little different like avatar component.
so, that's why I used it.
Thank you

2024-07-03 22:24 UTC, gilbertoaceville requested changes
@Tunki1201, Do you not understand why I ask you to not use radix-ui for some elements like "input"? We already have an input component(Find it and reuse that) or some of these elements do not require the additional features by radix ui. 

We are trying to cut out excesses in the codebase. [Discord Link](https://discord.com/channels/999382051935506503/1225528484705730681/1258140683961634907)

Do make the necessary changes.

2024-07-03 22:24 UTC, gilbertoaceville commented on modules/platform/agentbuilder/components/button/index.tsx
> +import * as React from "react"
We already have a button component in `shared/components/ui/Button/index.tsx`?  Use that.

This is redundant. One of the reasons we use `React` or `Next.js` as a framework is because of code reusability. If you cannot reuse components, you might as well build with `HTML`. [https://www.freecodecamp.org/news/intro-to-react-components/](https://www.freecodecamp.org/news/intro-to-react-components/)

2024-07-03 22:24 UTC, gilbertoaceville commented on modules/platform/agentbuilder/index.tsx
> + */
Remove this !!!

2024-07-03 22:24 UTC, gilbertoaceville commented on modules/platform/agentbuilder/index.tsx
> +                </div>
We do not need a chat interface. [Discord chat link](https://discord.com/channels/999382051935506503/1225528484705730681/1258083208164151369)

2024-07-07 22:29 UTC, closed without merging