FEAT/add-copy-button-to-copy-code
kyegomez/swarms-platform pull request #83
Opened 2024-06-09 08:47 UTC by Tunki1201

FEAT/add-copy-button-to-copy-code of module page

2024-06-10 10:56 UTC, gilbertoaceville reviewed
Make the necessary changes and merge.

2024-06-10 10:56 UTC, gilbertoaceville commented on shared/components/code-box/index.tsx
> +
Create a custom hook called `useCopy`, this code will be reuseable in the near future.

2024-06-10 10:57 UTC, gilbertoaceville requested changes
Make the necessary changes on `shared/components/code-box/index.tsx`(a comment was left there) and merge.

2024-06-10 11:29 UTC, Tunki1201 commented on shared/components/code-box/index.tsx
> +
ok

2024-06-10 11:30 UTC, Tunki1201 commented on shared/components/code-box/index.tsx
> +
thank you for your review. I think the copy feature is needed on code box

2024-06-11 09:09 UTC, gilbertoaceville approved these changes

2024-06-11 09:09 UTC, merged